services: 
  web:
    build: .
    image: farm-backend
    container_name: farm_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
<<<<<<< HEAD
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/uzhathunai_db_v2
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
=======
      DATABASE_URL: postgresql://postgres:postgres@db:5432/farm_db
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
>>>>>>> a8f27eb (Update docker setup and requirements)
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:15-3.3
    container_name: farm_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: farm_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
